### ISSUE TITLE
Generator Failing

### ISSUE THREAD

**Issue by newtriks** [kristoferjoseph/sprout-robotlegs#3]
Hi,

Seems this issue is preventing mediator/command etc classes being generated:

 /Users/newtriks/.rvm/gems/ruby-1.9.2-p136/gems/robotlegs-1.3.0.5.pre/lib/robotlegs/generators/mediator_generator.rb:11:in `manifest': undefined local variable or method`no_test' for #Robotlegs::MediatorGenerator:0x00000100dfa358 (NameError)
from /Users/newtriks/.rvm/gems/ruby-1.9.2-p136/gems/sprout-1.1.10.pre/lib/sprout/generator/base.rb:153:in `prepare_command'

**Comment by kristoferjoseph** [comment]
This is actually due to the main sprout flash sdk gem needing to be updated. Since the rl generators extend the flash sdk class generators this error started showing up when the sdk gem was refactored. This was fixed some time ago. Update both of the gems from github source and it will work.
